### ISSUE TITLE
Could not find adb error

### ISSUE THREAD

**Issue by Jimmys7156** [sdushantha/meobrute#1]
i copied all of the files from the platform-tools folder with adb in it into the folder with meobrute.sh, but it still says could not find adb when i try to run it

**Comment by sdushantha** [comment]
What OS are you running?

**Comment by Jimmys7156** [comment]
I ended up just inputting the code manually from your video, nothing came
up when I selected the hashed passcode though

**Comment by sdushantha** [comment]
That's odd.

Could you try the following:
1. Type in your MEO pin code and login into MEO
2. Now try the code to fetch the hash

**Comment by Jimmys7156** [comment]
I’ve been trying to recover the pin from my old account from a couple years
ago, I don’t actually know it.

**Comment by Jimmys7156** [comment]
[image: image.png]
This is the code, let me know if I've done anything wrong. thank you.

**Comment by sdushantha** [comment]
The image is not visible. Maybe try replying on GitHub instead of email

**Comment by Jimmys7156** [comment]
![image](https://user-images.githubusercontent.com/102559287/161609622-e625625b-0aeb-4100-a0a8-3920b8f1c46a.png)

**Comment by sdushantha** [comment]
If you go back to the YouTube video, there a pined comment. That should be the answer to the issue you are having

**Comment by Jimmys7156** [comment]
Thank you, I was able to figure that out myself. Are you continuing to do
research on this? I’m very curious if you’d be able to get the pin from an
unknown login, maybe by tricking Snapchat into thinking you’ve logged in
before. I’m not too experienced in coding or anything, so that was just a
random idea haha. I’m definitely interested in anything you find further
though.

**Comment by sdushantha** [comment]
Snapchat is an interesting app and I'll continue researching about this and other parts of Snapchat. If you like projects like this one, maybe [snaprecovery](https://github.com/sdushantha/snaprecovery) might be of interest for you.
