### ISSUE TITLE
Any other methods?

### ISSUE THREAD

**Issue by cpu2020** [sdushantha/meobrute#4]
Hello sdus,
im a big fan of your work especially sherlock I'm just wondering if there is anyway to complete this brute forcing WITHOUT root as id love to test this but my device is not rootable 

-- 
Cpu

**Comment by sdushantha** [comment]
Hey @cpu2020! Thank you for your kind words :)
There is unfortunetly no method to do this without root. But if you want to test the script, you can always install an Android emulator like Genymotion or Bluetstacks which has root. Then you can install Snapchat on it and test the script

**Comment by cpu2020** [comment]
> Hey @cpu2020! Thank you for your kind words :) There is unfortunetly no method to do this without root. But if you want to test the script, you can always install an Android emulator like Genymotion or Bluetstacks which has root. Then you can install Snapchat on it and test the script




Perfect! i didnt know about the emulators thank you very much for your help :)




--
cpu
