### ISSUE TITLE
Which OS and can it run on windows?

### ISSUE THREAD

**Issue by C-qmb** [sdushantha/meobrute#5]
Hi sdus,
I'm quite interested in your script here and would like to know which operating system did you use during your demo video, as in which Linux distro was it.. Id also like to know whether there's a way to make this work with windows too.. 

Regards,

**Comment by sdushantha** [comment]
In the demo I used Arch Linux. This script is written in Bash, so if you have WSL or some way of running bash, this script may work. But I'd suggest using this script on Linux as you may encounter issues when connecting the Android device to WSL or wherever you are running Bash in Windows.
