### ISSUE TITLE
Youtube Video

### ISSUE THREAD

**Issue by khmer96** [sdushantha/meobrute#6]
Can you re-up the youtube video?

**Comment by sdushantha** [comment]
@khmer96 YouTube deleted the video and they gave me a strike. I already have had strikes so I doubt I reupload it there. Odysee.com may be an alternative place to move my videos

**Comment by khmer96** [comment]
Will you upload it on Odysee? Trying to get back into my eyes only on my account

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
