### ISSUE TITLE
empty tables

### ISSUE THREAD

**Issue by Harkyzera** [sdushantha/meobrute#9]
The database normally presents information about the memories, among other things, but the important part, which would be the encrypted password, has absolutely nothing. All tables are empty. Can you confirm whether this method continues to work normally or has it been modified by Snapchat?

**Comment by sdushantha** [comment]
Hi @Harkyzera, I no longer have a rooted Android device so I'm unable to check if this still works. But I would not be surprised if Snapchat has made some changes.
